-- TapReview: migration 002
-- Makes sure businesses.id is filled in automatically for new rows
-- (needed by the admin panel). Safe to run several times.

do $id$
declare
  next_id bigint;
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'businesses'
      and column_name = 'id'
      and (is_identity = 'YES' or column_default is not null)
  ) then
    raise notice 'businesses.id is already automatic, nothing to do';
    return;
  end if;

  select coalesce(max(id), 0) + 1
    into next_id
    from public.businesses;

  execute format(
    'alter table public.businesses '
    'alter column id add generated by default as identity '
    '(start with %s)',
    next_id
  );
end
$id$;
